---
title: "Research"
---

__Complete List of Work__

**Select Working Papers**

1\. [The Subsidy to Infrastructure as an Asset Class](https://www.nber.org/papers/w25045) (with Aleksandar Andonov and Roman Kräussl), September 2018 

2\. [The Return Expectations of Institutional Investors](https://www.gsb.stanford.edu/faculty-research/working-papers/return-expectations-institutional-investors) (with Aleksandar Andonov), February 2019.

**Work in Progress**

1\. Behavioral Responses to California Income Taxation

2\. Fiscal Implications of Pension Underfunding

**Journal Publications**

1\. [State Taxation and the Reallocation of Business Activity: Evidence from Establishment-Level Data]('https://www.nber.org/papers/w21534') (with Xavier Giroud), 2017, Journal of Political Economy, Forthcoming

2\. [Political Representation and Governance: Evidence from the Investment Decisions of Public Pension Funds](https://www.semanticscholar.org/paper/Political-Representation-and-Governance-%3A-Evidence-Andonov-Hochberg/9c83dbd8b225848136e955f24477c6b9a0258300) (with Aleksandar Andonov and Yael Hochberg), 2017, Journal of Finance, Forthcoming

3\. [Linking Benefits to Investment Performance in US Public Pension Systems](https://www.nber.org/papers/w18491), 2014, Journal of Public Economics 116, 47-61.

4\. [The Revenue Demands of Public Employee Pension Promises](https://www.nber.org/papers/w18489), 2014, American Economic Journal: Economic Policy 6(1), 193-229.

5\. [It's the Market: The Broad-Based Rise in the Return to Top Talent](https://www.gsb.stanford.edu/faculty-research/publications/its-market-broad-based-rise-return-top-talent), Summer 2013, Journal of Economic Perspectives 27(3), 35-56.

6\. [Family, Education, and Sources of Wealth Among the Richest Americans, 1982-2012](https://www.jstor.org/stable/23469721?seq=1#metadata_info_tab_contents), 2013, American Economic Review P&P 103(3), 158-162.

7\. [Local Overweighting and Underperformance: Evidence from Limited Partner Private Equity Investments](https://www.nber.org/papers/w17122) (with Yael Hochberg), 2013, Review of Financial Studies 26(2), 403-451

8\. [Explaining Corporate Capital Structure: Product Markets, Leases, and Asset Similarity](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.423.4524&rep=rep1&type=pdf), latest version June 2011, Review of Finance 16(1), 115-155

9\. [Fiscal Imbalances and Borrowing Costs: Evidence from State Investment Losses](https://www.aeaweb.org/articles?id=10.1257/pol.4.2.182), latest version March 2011, American Economic Journal: Policy, Forthcoming

10\. [Public Pension Promises: How Big Are They and What Are They Worth?](https://www.semanticscholar.org/paper/Public-Pension-Promises-%3A-How-Big-Are-They-and-What-Novy-Marx-Rauh/2c3db8bc61184d9380f8b291639dc419d89fa133)(with Robert Novy-Marx), Journal of Finance 66(4), 2011, 1207-1245 

Winner, 2011 Smith Breeden Prize, First Prize Paper for the best capital markets paper published in the Journal of Finance State breakdown of $2.5 trillion unfunded public pension liability at the state level

11\. [Policy Options for State Pension Systems and Their Impact on Plan Liabilities](https://www.nber.org/papers/w16453) (with Robert Novy-Marx), Journal of Pension Economics and Finance 10(2), 173-194

12\. [Capital Structure and Debt Structure](https://www.nber.org/papers/w14488), Review of Financial Studies 23(12), 2010, 4242-4280.

13\. [The Liabilities and Risks of State-Sponsored Pension Plans](https://www.semanticscholar.org/paper/The-Liabilities-and-Risks-of-State-Sponsored-Plans-Novy-Marx-Rauh/32c39e18c24da51e87522dfc15e40d43d99507ef) (with Robert Novy-Marx), Journal of Economic Perspectives 23(4), 2009, 191-210.

14\. [Wall Street and Main Street: What Contributes to the Rise in the Highest Incomes?](https://www.nber.org/papers/w13270) (with Steven N. Kaplan), Review of Financial Studies 23(3), 2010, 1004-1050.

15\. [Risk Shifting versus Risk Management: Investment Policy in Corporate Pension Plans](https://www.nber.org/papers/w13240), Review of Financial Studies 22(7), 2009, 2687-2734.

16\. [Defined Contribution Plans, Defined Benefit Plans, and the Accumulation of Retirement Wealth (with James Poterba, Steven Venti, and David Wise)](https://www.nber.org/papers/w12597) Journal of Public Economics 91(10), 2007, 2062-2086.

17\. [Own Company Stock in Defined Contribution Pension Plans: A Takeover Defense?](https://www.sciencedirect.com/science/article/pii/S0304405X06000195), Journal of Financial Economics 81(2), 2006, 379-410.

18\. [Earnings Manipulation and Managerial Investment Decisions: Evidence from Sponsored Pension Plans](https://www.nber.org/papers/w10543), Quarterly Journal of Economics 121(1), 2006, 157-195 

Winner, 2004 Barclays Global Investor Best Symposium Paper of the European Finance Association

19\. [Investment and Financing Constraints: Evidence from the Funding of Corporate Pension Plans](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.453.2750), Journal of Finance 61(1), 2006, 33-71.

Winner, 2006 Brattle Prize, First Prize Paper for the best corporate finance paper published in the Journal of Finance

Winner, 2004 Western Finance Association Award for best corporate finance paper

**Some Popular Writing and Interviews**

1\. [Hidden Debt, Hidden Deficits: How Pension Promises Are Consuming State And Local Budgets](https://www.hoover.org/research/hidden-debt-hidden-deficits-2017-edition), 2017 Edition, Hoover Institution Essay.

2\. [Unfunded Pension Debts of U.S. States Still Exceed $3 Trillion](https://www.forbes.com/sites/pensionresearchcouncil/2015/08/25/unfunded-pension-debts-of-u-s-states-still-exceed-3-trillion/#5d1052d94d6a), 25 August 2015, Forbes Investing blog hosted by the Pension Research Council.

3\. [Funding Retiree Healthcare Plans](https://www.hoover.org/research/funding-retiree-healthcare-plans) (with Robert Pozen), Defining Ideas, 19 August 2015

4\. [Relief for Cities’ Budget Busting Health Care Costs](https://www.brookings.edu/blog/usc-brookings-schaeffer-on-health-policy/2015/07/26/relief-for-cities-budget-busting-health-care-costs/) (with Robert Pozen), Wall Street Journal, 26 July 2015

5\. [Averting the Public Pension Crisis without a National Insurance Agency](https://www.hoover.org/research/averting-public-pension-crisis-without-national-insurance-agency), Advancing a Free Society, 6 August 2013

6\. [Podcast on EconTalk with Russ Roberts](http://www.econtalk.org/joshua-rauh-on-public-pensions/), 5 November 2012

7\. [Start Paying or Stop Promising](https://www.nytimes.com/roomfordebate/2011/02/27/why-not-401ks-for-public-employees/start-paying-or-stop-promising), New York Times Room For Debate, 27 February 2011

**Materials on Retirement Finance**

1\. [Webinar: Investment Strategies for Long-Term Financial Planning](https://www.youtube.com/watch?v=nbzRBLHU3MI), 7 November 2013 with Josh Rauh (Moderator), William F. Sharpe, John Ameriks, and John Cuniff

2\. [Webinar: The Crisis in Public Employee Pensions](https://www.youtube.com/watch?v=Mn8SYkjcz3k&feature=youtu.be), 5 December 2013
with Josh Rauh (Moderator), Richard Ravitch, Sean McShea, David Crane, and Mark Dingley

**Other Publications**

1\. [Why City Pension Problems Have Not Improved, and a Roadmap Forward](https://www.hoover.org/research/why-city-pension-problems-have-not-improved-and-roadmap-forward), 2016, in Public Pensions and City Solvency, ed. Susan Wachter, Philadelphia: University of Pennsylvania Press.

2\. The Broad-Based Rise in the Return to Top Talent, 2015, in Inequality and Economic Policy: Essays in Memory of Gary Becker, ed. Stanford: Hoover Press.

3\. [Financial Valuation of PBGC Insurance with Market-Impllied Default Probabilities](https://www.nber.org/chapters/c13053) (with Robert Novy-Marx and Jules van Binsbergen), 2014, Tax Policy and the Economy 28, 133-154.

4\. The Crisis in Local Government Pensions in the United States (with Robert Novy-Marx), 2011, in Growing Old: Paying for Retirement and Institutional Money Management after the Financial Crisis, Robert Litan and Richard Herring, eds., Brookings Institution, Washington, DC.

Contains city and county breakdown of $0.6 trillion unfunded liabilities at the local level

[Related comment in the New York Times Room for Debate Blog](https://www.nytimes.com/roomfordebate/2011/02/06/will-new-york-citys-pensions-be-cut/on-pensions-when-will-we-face-reality)

Covered in the Washington Post, 12 October 2010

Front page of the Philadelphia Inquirer, 13 October 2010 

5\. Are State Public Pensions Sustainable? Why the Federal Government Should Worry About State Pension Liabilities, National Tax Journal 63(3), 2010 (Forum)

[Related Blog Post](https://kelloggfinance.wordpress.com/2010/03/22/the-day-of-reckoning-for-state-pension-plans/)

6\. [Utility Evaluation of Risk in Retirement Saving Accounts](www.nber.org/chapters/c10356), 2005, in Analyses in the Economics of Aging, David A. Wise (ed), University of Chicago Press.

7\. [Lifecycle Asset Allocation Strategies and the Distribution of 401(k) Retirement Wealth (with James Poterba, Steven Venti and David Wise)](www.nber.org/papers/w11974) in Developments in the Economics of Aging, David A. Wise (ed), University of Chicago Press, forthcoming.

8\. How Elastic is the Corporate Income Tax Base? (with Jonathan Gruber) in Taxing Corporate Income in the 21st Century, Cambridge University Press, Alan Auerbach, James R. Hines, and Joel Slemrod (eds.), 2007.

9\. [Why Are Firms in the United States Abandoning Defined Benefit Plans?](http://icpmnetwork.com/research-paper/why-are-firms-in-the-united-states-abandoning-defined-benefit-plans/) Rotman Journal of Pension Management 2(2), 2009, 18-25

**Some Resources on the State Pension Crisis**

1\. [Congressional Testimony](https://www.pensions.senate.gov/content/how-multiemployer-pension-system-affects-stakeholders)

2\. [The Pension Bomb, The Milken Institute Review, 2011Q1](https://www.milkeninstitute.org/publications/view/449)

**Opinions and Blog Posts**

1\. The Looming Shortfall in Public Pension Costs, Washington Post, 19 October 2012

2\. [On Pensions, When Will We Face Reality](https://www.nytimes.com/roomfordebate/2011/02/06/will-new-york-citys-pensions-be-cut/on-pensions-when-will-we-face-reality)

Posted on New York Times Room For Debate, 7 February 2011

3\. [Return Assumptions: It's All Just Borrowing in Disguise](https://kelloggfinance.wordpress.com/2010/09/20/return-assumptions-its-all-just-borrowing-in-disguise/), Posted on Everything Finance, 20 September 2010

4\. Can the Illinois Pension Catastrophe Be Stopped, Chicago Tribune, 13 Aug 2010

5\. Pension Security Bonds: A New Plan to Address the Pension Crisis (with Robert Novy-Marx), The Economists' Voice 7(3), 2010

[Very short version on the New York Times blog "Room for Debate", 20 May 2010](https://roomfordebate.blogs.nytimes.com/2010/05/20/can-states-fix-their-pension-problems/#joshua)

6\. [Illinois' Irrelevant Pension Reform](https://kelloggfinance.wordpress.com/2010/04/15/illinois-irrelevant-pension-reform/)

Posted on Everything Finance, 15 April 2010

7\. [The Day of Reckoning for State Pension Plans](https://kelloggfinance.wordpress.com/2010/03/22/the-day-of-reckoning-for-state-pension-plans/)

Posted on Everything Finance, 22 March 2010

8\. [A Bankruptcy to Save GM](https://voxeu.org/article/gm-solution-chapter-11-government-restructuring-finance), 19 November 2008

**Other Papers**

1\. The Effects of Financial Condition on Capital Investment and Financing: Evidence from Variation in Pension Fund Asset Performance

2\. [The Intergenerational Transfer of Public Pension Promises](https://www.nber.org/papers/w14343) (with Robert Novy-Marx)

3\. [Funding Soft Liabilities](https://www.nber.org/chapters/c13294) (with Robert Novy-Marx)

<style type="text/css">

body{ /* Normal  */
      font-family: Helvetica;
      font-size: 11px;
  }
td {  /* Table  */
  font-size: 8px;
  color: Black;
}
h1.title {
  font-size: 20px;
  color: Maroon;
}

